version: '3.7'

services:
  # Layanan MySQL untuk Development
  mysql_devel:
    container_name: mysql_devel_container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Telkom123!
      MYSQL_DATABASE: academics_devel
    volumes:
      - mysql_data_devel:/var/lib/mysql
    networks:
      - devel_network
    ports:
      - "3307:3306"

  # Layanan MySQL untuk Production
  mysql_prod:
    container_name: mysql_prod_container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Telkom123!
      MYSQL_DATABASE: academics
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - prod_network
    ports:
      - "3308:3306"

  # Layanan SonarQube
  sonarqube:
    container_name: sonarqube_container
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=Telkom123!
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - JAVA_OPTS=-Xmx1g -Xms512m
    deploy:
      resources:
        limits:
          memory: 2g
    depends_on:
      - sonar_db
    networks:
      - devel_network

  # Database untuk SonarQube (PostgreSQL)
  sonar_db:
    container_name: sonarqube_db_container
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: Telkom123!
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - devel_network

# Volume untuk MySQL dan SonarQube
volumes:
  mysql_data_devel:
  mysql_data_prod:
  sonar_db_data:

# Jaringan
networks:
  devel_network:
    driver: bridge
  prod_network:
    driver: bridge