name: CD Example Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4
      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Berhasil Konek ke Server"
            if [ -d "/home/jack" ]; then
              echo "Ada folder CICD_Database"
              cd /home/jack
              echo "Berhasil Masuk ke Folder CICD_Database"
            else
              echo "Gagal Masuk ke Folder CICD_Database"
            fi
            
