name: CICD Database Dev to Prod

on:
  push:
    branches: 
      - main

jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout the repository
      - name: SSH Connect
        uses: appleboy/ssh-action@v1 # SSH Connect
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil Konek ke Server"

            cd /home/jack/CICD_DATABASE
            echo "Berhasil masuk ke direktori CICD_DATABASE"

            docker compose up -d 
            echo "Berhasil menjalankan Docker Compose"